name: SLab Build
on:
  push:
    branches:
      - master
jobs:
  OpenSilver-Build:
    #We should not run these steps on the forks by default.
    #if: github.repository_owner == 'OpenSilver'
    runs-on: windows-2019
    steps:
      - uses: microsoft/setup-msbuild@v1.0.3
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Clone SLab repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Restore Packages
        run: |
          nuget restore Source/SLaB.OpenSilver.sln -v quiet
      - name: Build SLab
        working-directory: Source
        run: msbuild SLaB.OpenSilver.sln -t:build -p:Configuration=Release -clp:ErrorsOnly -restore
      - name: Format Package Version
        id: version
        run: echo "::set-output name=suffix::$(date +'%Y-%m-%d-%H%M%S')-${{ env.GITHUB_SHA_SHORT }}"
      - name: Pack SLab
        working-directory: build
        run: |
          mkdir temp; echo "OpenSilver 1.0.0-private-${{ steps.version.outputs.suffix }}" > temp/Version.txt
          nuget.exe pack nuspec\OpenSilver.nuspec -OutputDirectory "output/OpenSilver" -Properties "PackageId=OpenSilver;PackageVersion=1.0.0-private-${{ steps.version.outputs.suffix }};Configuration=SL;Target=OpenSilver;RepositoryUrl=https://github.com/${{ env.GITHUB_REPOSITORY_OWNER_PART }}/${{ env.GITHUB_REPOSITORY_NAME_PART }}"
      - uses: actions/upload-artifact@v2
        with:
          name: OpenSilver
          path: "build/output/SLab.Navigation"
      - name: Upload packages
        run: |
           dotnet nuget push "build\output\OpenSilver\*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/${{ env.GITHUB_REPOSITORY_OWNER_PART }}/index.json
      - name: Upload packages to MyGet
        run: |
           dotnet nuget push "build\output\OpenSilver\*.nupkg" -k ${{ secrets.MYGET_TOKEN }} -s https://www.myget.org/F/opensilver/api/v2/package     
